import logging

from .ast_change_vector import extract_features
from .ast_diff import flatten_ast
from .ast_similarity import ast_fingerprint
from .types import ExecutionResult
from .utils import ensure_workspace, step_number


logger = logging.getLogger(__name__)


def _render_valid_module(step: str, number: int) -> str:
    return (
        '"""Generated by the RNOS Agent Runtime executor."""\n\n'
        f"STEP_NUMBER = {number}\n"
        f"STEP_TEXT = {step!r}\n\n"
        "def run() -> str:\n"
        "    return f'executed step {STEP_NUMBER}: {STEP_TEXT}'\n\n"
        "if __name__ == '__main__':\n"
        "    print(run())\n"
    )


def _render_invalid_module(step: str, number: int) -> str:
    return (
        '"""Generated invalid patch used to exercise RNOS governance."""\n\n'
        f"STEP_NUMBER = {number}\n"
        f"STEP_TEXT = {step!r}\n\n"
        "def run() -> str:\n"
        "    return 'this file is intentionally malformed'\n\n"
        "if __name__ == '__main__':\n"
        "    print(run()\n"
    )


def execute_step(step: str) -> ExecutionResult:
    workspace = ensure_workspace()
    number = step_number(step)
    target = workspace / f"step_{number:02d}.py"

    try:
        unstable = number >= 3 or "invalid" in step.lower() or "unstable" in step.lower()
        source = (
            _render_invalid_module(step, number)
            if unstable
            else _render_valid_module(step, number)
        )
        target.write_text(
            source,
            encoding="utf-8",
        )
        logger.info("executor.wrote_file", extra={"path": str(target)})
        return ExecutionResult(
            success=True,
            output=f"wrote {target}",
            artifact_path=str(target),
            ast_fingerprint=ast_fingerprint(source),
            ast_tokens=flatten_ast(source),
            ast_features=extract_features(source),
        )
    except OSError as exc:
        logger.exception("executor.failed")
        return ExecutionResult(success=False, output="", error=str(exc))
